---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create public key for management server root user
      user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=/root/.ssh/id_rsa.pub

    - name: Create public key for management server cumulus user
      user: name=cumulus generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=/home/cumulus/.ssh/id_rsa.pub

    - name: Copy root key into authorized keys on web server
      copy: src=/root/.ssh/id_rsa.pub dest=/var/www/html/authorized_keys

    - name: Copy cumulus key into authorized_keys on web server
      copy: src=/root/.ssh/id_rsa.pub dest=/var/www/html/authorized_keys

- hosts: network
  sudo: yes
  tasks:
    - name: Make ssh dir for cumulus user
      file: path=/home/cumulus/.ssh state=directory mode=0755

    - name: Copy authorized key for Cumulus user
      copy: src=/var/www/html/authorized_keys dest=/home/cumulus/.ssh/authorized_keys

    - name: Make ssh dir for root user
      file: path=/root/.ssh state=directory mode=0755

    - name: Copy authorized key for root user
      copy: src=/var/www/html/authorized_keys dest=/root/.ssh/authorized_keys

- hosts: servers
  sudo: yes
  tasks:
    - name: Create cumulus user
      user: name=cumulus shell=/bin/bash groups=sudo

    - name: Make ssh dir for cumulus user
      file: path=/home/cumulus/.ssh state=directory mode=0755

    - name: Copy authorized key for Cumulus user
      copy: src=/var/www/html/authorized_keys dest=/home/cumulus/.ssh/authorized_keys

    - name: Make ssh dir for root user
      file: path=/root/.ssh state=directory mode=0755

    - name: Copy authorized key for root user
      copy: src=/var/www/html/authorized_keys dest=/root/.ssh/authorized_keys
