---
- hosts: network
  remote_user: root
  tasks:
  - name: create directory for ansible custom facts
    file: state=directory recurse=yes path=/etc/ansible/facts.d

  - name: copy facts to remote machine
    copy: src={{ item }} dest=/etc/ansible/facts.d/ mode=755
    with_items:
      - bgpsum.fact
      - bgproute.fact

  - name: read in facts
    setup: filter=ansible_local

  - meta: flush_handlers

  - debug: msg="total number of peers is {{ ansible_local.bgpsum.totalPeers }}"
    changed_when: "ansible_local.bgpsum.totalPeers == 6"
    when: inventory_hostname in groups.spine

  - debug: msg="total number of peers is {{ ansible_local.bgpsum.totalPeers }}"
    changed_when: "ansible_local.bgpsum.totalPeers == 2"
    when: inventory_hostname in groups.leaf

  - debug: msg="number of bgp routes {{ ansible_local.bgproute.routes|length }}"
    changed_when: "ansible_local.bgproute.routes|length == 2"
