---
- hosts: network
  remote_user: root
  tasks:

  - debug: msg="{{ ansible_hostname }} has {{ ansible_local.bgpsum.totalPeers }} BGP Peers"
    failed_when: "ansible_local.bgpsum.totalPeers != 6"
    when: inventory_hostname in groups.spine

  - debug: msg="{{ ansible_hostname }} has {{ ansible_local.bgpsum.totalPeers }} BGP Peers"
    changed_when: "ansible_local.bgpsum.totalPeers != 2"
    when: inventory_hostname in groups.leaf

  - debug: msg="{{ ansible_hostname }} has {{ ansible_local.bgproute.routes|length }} BGP Routes"
    changed_when: "ansible_local.bgproute.routes|length != 13"

  - set_fact: 
      ips: []
  - set_fact: 
      ips: "{{ ips + hostvars[item].ansible_all_ipv4_addresses }}"
    with_inventory_hostnames: network

  - name: ping all other IPs in the CLOS
    shell: "ping {{ item }} -c 1"
    with_items:
      - "{{ ips }}"
    register: result
    changed_when: "result.rc != 0"

